#!/bin/bash
# Back up a root partition to another partition on a SATA SSD.

script="$(dirname $(realpath "$0"))/backup-partition"
if [ ! -e "$script" ]; then
    script="$(dirname $(realpath "$0"))/../linux/backup-partition"
fi
if [ ! -e "$script" ]; then
    echo "Could not find backup-partition script" >&2; exit 1
fi
HOSTNAME="${HOSTNAME-$(hostname)}"

verbose=
while [ "$#" -gt 0 ]; do
    case "$1" in
        -v|--verbose)  verbose="$1"; shift ;;
    esac
done

if [ "`id -u`" != 0 ]; then
    echo "Warning: not root.  (Try with ssudo?)" >&2
fi

"$script" $verbose --write-times /common/backups/last_backup.root_sata \
          --root \
          -X .cache -X .gvfs LABEL="root" LABEL="sata_root" \
          --data \
          LABEL="EFI_SYS" LABEL="SATA_EFISYS"
