#!/bin/bash
# Back up a root partition to another partition.

script="`dirname "$0"`/backup-partition"
HOSTNAME="${HOSTNAME-$(hostname)}"

verbose=
while [ "$#" -gt 0 ]; do
    case "$1" in
        -v|--verbose)  verbose="$1"; shift ;;
    esac
done

if [ "`id -u`" != 0 ]; then
    echo "Warning: not root.  (Try with ssudo?)" >&2
fi

"$script" $verbose --write-times /common/backups/last_backup.root_sata \
          --root \
          -X .cache -X .gvfs LABEL="root" LABEL="hg_root" \
          --data \
          LABEL="EFI_SYS" LABEL="HG_EFI_SYS"
