#!/bin/sh

fail () {
    if [ "$#" -eq 0 ]; then set -- "Something has gone very wrong!"; fi
    echo "$*" >&2
    exit 1
}

status () {
    echo "-- [`date +'%Y-%m-%d %H:%M:%S'`] -- $*"
}

backup=/backup
full_backup="home scratch"
tar_backup="root boot"

dryrun=

while [ "$#" -gt 0 ]; do
    case "$1" in
       -n)  dryrun=yes ;;
       -*)  fail "Unknown flag '$1'" ;;
        *)  fail "Unexpected argument '$1'" ;;
    esac
    shift
done

[ -n "`mount | awk '($3 == "'"$backup"'")'`" ] \
    || fail "$backup isn't mounted!"

Run () {
    if [ -n "$dryrun" ]; then echo "WOULD run:      $*" >&2; else "$@"; fi
}
TimeRun () {
    if [ -n "$dryrun" ]; then echo "WOULD run: time $*" >&2; else time "$@"; fi
}

TestBad () {
    if [ -n "$dryrun" ]; then false;  else test "$@";  fi
}
TestGood () {
    if [ -n "$dryrun" ]; then true;   else test "$@";  fi
}

run_backup () {
    local src="$1"
    local dst_base="$2"
    local dst_ext="$3"
    local dst="$dst_base$dst_ext"

    set --
    for ext in '' '.tar.gz' '.tar.bz2'; do
	local xdst="$dst_base$ext"
	if [ -e "$xdst.old" -a -e "$xdst" ]; then
	    status "Cleaning up previous $xdst..."
	    Run rm -rf "$xdst.old" || fail "couldn't remove $xdst.old"
	    TestBad -e "$xdst.old" && fail "didn't actually remove $xdst.old"
	    status "...done."
	fi
	if [ -e "$xdst" ]; then
	    set -- "$@" "$xdst"
	    Run mv "$xdst" "$xdst.old" || fail "couldn't move old $xdst"
	fi
    done

    status "Backing up $src to $dst..."
    case "$dst" in
	*.tar.gz)
	    TimeRun tar -C "$src" --one-file-system -czf "$dst" . \
		|| fail "The tarballing went kaboom."
	    ;;
	*.tar.bz2)
	    TimeRun tar -C "$src" --one-file-system -cjf "$dst" . \
		|| fail "The tarballing went kaboom."
	    ;;
	*)
	    Run mkdir -p "$dst" || fail "couldn't create new directory $dst"
	    (TimeRun tar -C "$src" --one-file-system -cf - . \
		| Run tar -C "$dst" -xpf -) || fail "The copying went kaboom."
	    ;;
    esac
    status "...done."

    for xdst in "$@"; do
	status "Cleaning up previous $xdst..."
	Run rm -rf "$xdst.old"
	status "...done."
    done
}

partition_path () {
    if [ "$1" = "root" ]; then echo "/"; else echo "/$1"; fi
}
backup_path () {
    echo "$backup/$1"
}

run_all_backups () {
    for i in $full_backup; do
	run_backup "`partition_path $i`" "`backup_path $i`" ""
    done

    for i in $tar_backup; do
	run_backup "`partition_path $i`" "`backup_path $i`" ".tar.gz"
    done
}

if [ -t 1 ]; then
    # Only create a log file if the output is being sent to a terminal,
    # and if this isn't a dry run.
    log="$backup/log.`date +'%Y-%m-%d'`.txt"
    if [ -e "$log" ]; then
	log="$backup/log.`date +'%Y-%m-%d.%H-%M'`.txt"
	if [ -e "$log" ]; then
	    for x in a b c d e f g h i j k l m n o p q r s t u v w x y z; do
		log="$backup/log.`date +'%Y-%m-%d.%H-%M'`.$x.txt"
		if [ ! -e "$log" ]; then break; fi
	    done
	fi
    fi
    if [ -z "$dryrun" ]; then
	status "Will write log to $log"
	run_all_backups 2>&1 | tee "$log"
    else
	status "Would write log to $log"
	run_all_backups
    fi
else
    run_all_backups
fi
