#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Delete todos from Habitica
import argparse
import bert_habitica as bh


def delete_todo(settings, verbosity=0):
    client = bh.Habitica(verbosity=verbosity)
    client.delete_todo_by_name(text=settings.title)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('title')
    parser.add_argument('-v', '--verbose', action='count', default=0)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    delete_todo(settings, verbosity=settings.verbose)


if __name__ == "__main__":
    main()
