#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# List all frames (text label and ID) for the specified board.
import argparse
from bert_miro import get_board


def print_groups(
    board_key: str,
    verbosity: int = 0,
    print_group_url: bool = False,
    print_item_urls: bool = False,
) -> None:
    board = get_board(board_key, board_key, verbosity=verbosity)
    for group in board.groups():
        to_print: list[str] = [repr(group)]
        if print_group_url:
            # Note: group.link is API-oriented, can't be used from e.g.
            # a browser!
            to_print.append(
                "https://miro.com/app/board/" + board_key + "/?moveToWidget=" + group.id
            )
        print(", ".join(to_print))
        for item_id in group.item_ids or []:
            item = board.item_by_id(item_id)
            to_print = [repr(item)]
            if print_item_urls:
                to_print.append(
                    "https://miro.com/app/board/"
                    + board_key
                    + "/?moveToWidget="
                    + item_id
                )
            print("    " + ", ".join(to_print))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("board")
    settings = parser.parse_args()
    return settings


def main() -> None:
    settings = parse_args()
    print_groups(
        settings.board,
        verbosity=settings.verbose,
        print_group_url=(settings.verbose >= 2),
    )


if __name__ == "__main__":
    main()
