#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Realign sticky notes in the specified frame.
import argparse
from enum import Enum
from typing import Mapping

from bert_miro import (
    get_board,
    get_frame,
    create_item_id_to_group_mapping,
    StickyNote,
    Group,
)
from bert_miro_grid import (
    GridSpacingMode,
    StickyNoteGrid,
)


class GridAxes(Enum):
    X_AND_Y = "xy"
    X_ONLY = "x"
    Y_ONLY = "y"


def move_with_group(
    sticky: StickyNote,
    dx: float,
    dy: float,
    *,
    dry_run: bool = False,
    verbosity: int = 0,
    group_map: Mapping[str, Group] | None = None,
) -> None:
    assert sticky.board is not None, f"Sticky note {sticky.id} has no board"
    if group_map is None:
        group_map = create_item_id_to_group_mapping(sticky.board)
    if sticky.id in group_map:
        group_obj = group_map[sticky.id]
        while group_obj.id in group_map:
            group_obj = group_map[group_obj.id]
        movable_items = group_obj.get_items_recursive()
    else:
        movable_items = [sticky]

    for item in movable_items:
        position = item.relative_position
        assert position is not None, f"Item {item.id} has no position"
        if not dry_run:
            if verbosity >= 1:
                print(f"Moving {item!r} by ({dx}, {dy})")
            item.set_relative_position((position[0] + dx, position[1] + dy))
        else:
            if verbosity >= 0:
                print(f"Would move {item!r} by ({dx}, {dy})")


def apply_axes(
    axes: GridAxes, *, old: tuple[float, float], new: tuple[float, float]
) -> tuple[float, float]:
    if axes == GridAxes.X_ONLY:
        return (new[0], old[1])
    elif axes == GridAxes.Y_ONLY:
        return (old[0], new[1])
    else:
        return new


def update_stickies(
    board_name_or_id: str,
    frame_name_or_id: str,
    *,
    spacing_mode: GridSpacingMode = GridSpacingMode.EQUAL,
    adjust_axes: GridAxes = GridAxes.X_AND_Y,
    dry_run: bool = False,
    verbosity: int = 0,
    print_empty_warnings: bool | None = None,
    print_grid_warnings: bool | None = None,
) -> None:
    print_empty_warnings = print_empty_warnings if print_empty_warnings is not None else verbosity >= 0
    print_grid_warnings = print_grid_warnings if print_grid_warnings is not None else verbosity >= 0

    board = get_board(board_name_or_id, board_name_or_id, verbosity=verbosity)
    frame = get_frame(board, frame_name_or_id, frame_name_or_id, verbosity=verbosity)

    sticky_notes = frame.sticky_notes()
    if not sticky_notes:
        if print_empty_warnings:
            print(
                f"No sticky notes found in frame {frame_name_or_id!r} on board {board_name_or_id!r}!"
            )
        return

    grid = StickyNoteGrid(sticky_notes)
    grid.check_grid_overlaps()
    if verbosity >= 0:
        smaller_most_common_size = min(grid.most_common_sticky_dimensions())
        spacing = grid.new_spacing(spacing_mode)
        size = grid.grid_size()

        # If the grid size is only 1 in a dimentsion, spacing doesn't matter so skip warning
        if spacing[0] < smaller_most_common_size and size[0] > 1 and print_grid_warnings:
            print(
                f"X spacing {spacing[0]} is smaller than sticky size {smaller_most_common_size}, proceeding anyway"
            )
        if spacing[1] < smaller_most_common_size and size[1] > 1 and print_grid_warnings:
            print(
                f"Y spacing {spacing[1]} is smaller than sticky size {smaller_most_common_size}, proceeding anyway"
            )

    xy_moves = tuple(
        (s, grid.sticky_original_position(s), grid.sticky_new_position(s, spacing_mode))
        for s in sticky_notes
    )
    moves = tuple((s, o, apply_axes(adjust_axes, old=o, new=n)) for s, o, n in xy_moves)

    if verbosity >= 1:
        min_old_x = min(m[1][0] for m in moves)
        max_old_x = max(m[1][0] for m in moves)
        min_old_y = min(m[1][1] for m in moves)
        max_old_y = max(m[1][1] for m in moves)
        min_new_x = min(m[2][0] for m in moves)
        max_new_x = max(m[2][0] for m in moves)
        min_new_y = min(m[2][1] for m in moves)
        max_new_y = max(m[2][1] for m in moves)

        print(f"Left   moving by {min_new_x - min_old_x:.3f}")
        print(f"Right  moving by {max_new_x - max_old_x:.3f}")
        print(f"Top    moving by {min_new_y - min_old_y:.3f}")
        print(f"Bottom moving by {max_new_y - max_old_y:.3f}")

    # Count how many are actually moving
    num_moving = 0
    for sticky, old_pos, new_pos in moves:
        dx, dy = new_pos[0] - old_pos[0], new_pos[1] - old_pos[1]
        if abs(dx) > 1e-6 or abs(dy) > 1e-6:
            num_moving += 1

    # Execute moves
    if num_moving > 0:
        group_map = create_item_id_to_group_mapping(board)
        for sticky, old_pos, new_pos in moves:
            dx, dy = new_pos[0] - old_pos[0], new_pos[1] - old_pos[1]
            if abs(dx) > 1e-6 or abs(dy) > 1e-6:
                move_with_group(
                    sticky,
                    dx,
                    dy,
                    group_map=group_map,
                    verbosity=verbosity,
                    dry_run=dry_run,
                )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("-q", "--quiet", action="store_const", dest="verbose", const=-1)
    parser.add_argument("--quiet-empty", action="store_true", default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--equal",
        action="store_const",
        dest="spacing_mode",
        const=GridSpacingMode.EQUAL,
        default=GridSpacingMode.EQUAL,
    )
    parser.add_argument(
        "--extend-strict",
        action="store_const",
        dest="spacing_mode",
        const=GridSpacingMode.INTERNAL_STRICT,
    )
    parser.add_argument(
        "--extend",
        action="store_const",
        dest="spacing_mode",
        const=GridSpacingMode.INTERNAL_OR_EQUAL,
    )
    parser.add_argument(
        "--tight",
        action="store_const",
        dest="spacing_mode",
        const=GridSpacingMode.TIGHT,
    )
    parser.add_argument(
        "--tiled",
        action="store_const",
        dest="spacing_mode",
        const=GridSpacingMode.TILED,
    )
    parser.add_argument(
        "--x-only",
        action="store_const",
        dest="adjust_axes",
        const=GridAxes.X_ONLY,
        default=GridAxes.X_AND_Y,
    )
    parser.add_argument(
        "--y-only",
        action="store_const",
        dest="adjust_axes",
        const=GridAxes.Y_ONLY,
    )
    parser.add_argument("board")
    parser.add_argument("frame")
    settings = parser.parse_args()
    return settings


def main() -> None:
    settings = parse_args()
    update_stickies(
        settings.board,
        frame_name_or_id=settings.frame,
        spacing_mode=settings.spacing_mode,
        adjust_axes=settings.adjust_axes,
        verbosity=settings.verbose,
        print_empty_warnings=False if settings.quiet_empty else None,
        dry_run=settings.dry_run,
    )


if __name__ == "__main__":
    main()
