#!/usr/bin/python3
# List all clients (name and ID) for the specified or default workspace
import argparse
import bert_toggl_track as trk


def process_clients(workspace_key, settings):
    ws = trk.get_workspace(workspace_key, verbosity=settings.verbose)
    for cl in ws.clients():
        if not cl.archived or settings.print_inactive:
            print("{}   {}, {}".format(('#' if cl.archived else ' '),
                                       repr(cl.id), repr(cl.name)))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    parser.add_argument('-a', '--print-inactive', action='store_true')
    parser.add_argument('workspace', nargs='?', default=None)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    process_clients(settings.workspace, settings)


if __name__ == "__main__":
    main()
