#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# List all workspaces (name and ID) for the user
import argparse
import bert_toggl_track as trk


def process_workspaces(settings):
    tt = trk.create_client()
    for ws in tt.workspaces():
        print("{}   {}, {}".format(' ', repr(ws.id), repr(ws.name)))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    process_workspaces(settings)


if __name__ == "__main__":
    main()
