#!/home/bert/.py_venv/tasks_000/bin/python3
# List all tags (name and ID) for the specified or default workspace
import argparse
import bert_toggl_track as trk


def process_tags(workspace_key, settings):
    ws = trk.get_workspace(workspace_key, verbosity=settings.verbose)
    for tag in ws.tags():
        print("{}   {}, {}".format(' ', repr(tag.id), repr(tag.name)))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    parser.add_argument('workspace', nargs='?', default=None)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    process_tags(settings.workspace, settings)


if __name__ == "__main__":
    main()
