#!/usr/bin/python3
# List all projects (name and ID) for the specified or default workspace
import argparse
import bert_toggl_track as trk


def process_projects(workspace_key, settings):
    ws = trk.get_workspace(workspace_key, verbosity=settings.verbose)
    for prj in ws.projects():
        if prj.active or settings.print_inactive:
            print("{}   {}, {}".format((' ' if prj.active else '#'),
                                       repr(prj.id), repr(prj.name)))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    parser.add_argument('-a', '--print-inactive', action='store_true')
    parser.add_argument('workspace', nargs='?', default=None)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    process_projects(settings.workspace, settings)


if __name__ == "__main__":
    main()
