#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# List all lists (name and ID) for the specified board.
import argparse
import trello  # type: ignore[import-untyped]
import trello.exceptions  # type: ignore[import-untyped]
from typing import Iterable, Protocol, cast
from bert_trello import get_board, create_auth_token, read_auth_data


class ListProtocol(Protocol):
    id: str
    name: str
    closed: bool


class BoardProtocol(Protocol):
    def list_lists(self) -> Iterable[ListProtocol]: ...


def print_lists(board_key: str, settings: argparse.Namespace) -> None:
    try:
        board = cast(
            BoardProtocol, get_board(board_key, board_key, verbosity=settings.verbose)
        )
    except trello.exceptions.Unauthorized:
        board = get_board(
            board_key,
            board_key,
            verbosity=settings.verbose,
            auth=create_auth_token(read_auth_data()),
        )
    for raw_list in board.list_lists():
        tlist = cast(ListProtocol, raw_list)
        is_closed = bool(tlist.closed)
        if not is_closed or settings.print_archived:
            fields: list[str] = []
            if settings.verbose > 0:
                fields.append(repr(tlist.id))
            fields.append(repr(tlist.name))
            print("{:3s} {}".format(("#" if is_closed else " "), ", ".join(fields)))
            if settings.verbose >= 2:
                import unicodedata

                name = str(tlist.name)
                nfc_name = unicodedata.normalize("NFC", name)
                if name != nfc_name:
                    print(
                        "      Note: name is different from its NFC form "
                        f"{nfc_name!r}"
                    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("-a", "--print-archived", action="store_true")
    # The Trello REST API currently no longer supports list deletion, and
    # py-trello no longer exposes the List function to delete a list.
    # If that changes, consider bringing back the functionality in a separate
    # script, like trello_delete_archived_cards_from_board.
    # In the meantime, though, it's possible to do it from the GUI!
    #   parser.add_argument('-d', '--delete-archived', action='store_true')
    parser.add_argument("board")
    settings = parser.parse_args()
    return settings


def main() -> None:
    settings = parse_args()
    print_lists(settings.board, settings)


if __name__ == "__main__":
    main()
