#!/usr/bin/python3
# List all lists (name and ID) for the specified board.
import argparse
import os.path
import regex
import subprocess
import sys
from bert_trello import get_board, create_auth_token, read_auth_data

def print_lists(board_key, verbosity=0):
    try:
        board = get_board(board_key, board_key, verbosity=verbosity)
    except trello.exceptions.Unauthorized as e:
        board = get_board(board_key, board_key, verbosity=verbosity,
                          auth=create_auth_token(read_auth_data()))
    for tlist in board.list_lists():
        if not tlist.closed or verbosity >= 1:
            print("{}   {}, {}".format(('#' if tlist.closed else ' '),
                                       repr(tlist.id), repr(tlist.name)))

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    parser.add_argument('board')
    settings = parser.parse_args()
    return settings

def main():
    settings = parse_args()
    print_lists(settings.board, verbosity=settings.verbose)

if __name__ == "__main__":
    main()
