#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Show template cards from a board (by default, 'bert active').
import argparse
from collections import defaultdict
import sys
import trello.exceptions  # type: ignore[import-untyped]
from bert_trello import (
    get_board,
    create_auth_token,
    read_auth_data,
    is_card_template,
    print_cards,
    Card,
)


def create_level_1() -> defaultdict[bool, list[Card]]:
    # Note: specifying the factory argument by name (default_factory=...)
    # as documented on docs.python.org fails with Python 3.11
    return defaultdict(list)


def create_level_2() -> defaultdict[str, defaultdict[bool, list[Card]]]:
    return defaultdict(create_level_1)


def process_cards(board_key: str, settings: argparse.Namespace) -> None:
    try:
        board = get_board(board_key, board_key, verbosity=settings.verbosity)
    except trello.exceptions.Unauthorized:
        board = get_board(
            board_key,
            board_key,
            verbosity=settings.verbosity,
            auth=create_auth_token(read_auth_data()),
        )
    seen = create_level_2()
    for card in board.open_cards():
        name: str = str(card.name)  # type: ignore[attr-defined]
        cards = seen[name][is_card_template(card)]
        cards.append(card)
        if settings.verbosity >= 0:
            # NOTE: does not follow the specified output settings
            print("+" if len(cards) > 1 else ".", end="", file=sys.stderr, flush=True)
    if settings.verbosity >= 0:
        print(file=sys.stderr, flush=True)
    for name in sorted(seen.keys()):
        name_dict = seen[name]
        templates = name_dict.get(True, [])
        non_templates = name_dict.get(False, [])
        if len(templates) > 0:
            print(f"{name!r} templates:")
            print_cards(templates)
            if settings.show_cards_with_templates and non_templates:
                print("  matching cards:")
                print_cards(non_templates)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Show template cards on a board (plus some other"
            " stuff depending on options selected)."
        )
    )
    parser.add_argument(
        "-v",
        "--verbose",
        dest="verbosity",
        action="count",
        default=0,
        help="Be more verbose. Can be repeated.",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        dest="verbosity",
        action="store_const",
        const=-1,
        help="Be non-verbose.",
    )
    parser.add_argument(
        "-c",
        "--show-cards-with-templates",
        "--show-cards",
        action="store_true",
        help=(
            "When showing templates, also show the" " corresponding non-template cards."
        ),
    )
    parser.add_argument("board", nargs="?", default="bert active")
    settings = parser.parse_args()
    return settings


def main() -> None:
    settings = parse_args()
    process_cards(settings.board, settings)


if __name__ == "__main__":
    main()
