#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# List all boards (name and ID) for the current user.
import argparse
import trello
from bert_trello import create_client, create_auth_token, read_auth_data


def print_boards(verbosity=0):
    client = create_client()
    try:
        boards = client.list_boards()
    except trello.exceptions.Unauthorized:
        client = create_client(create_auth_token(read_auth_data()))
        boards = client.list_boards()
    for board in boards:
        if not board.closed or verbosity >= 1:
            print("{}   {}, {}".format(('#' if board.closed else ' '),
                                       repr(board.id), repr(board.name)))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='count', default=0)
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    print_boards(verbosity=settings.verbose)


if __name__ == "__main__":
    main()
