#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# List all cards (showing the list name, card name, and optionally
# description and IDs) for the specified board.
import argparse
from functools import cache
import itertools
import trello.exceptions  # type: ignore[import-untyped]
from typing import cast
from bert_trello import (
    get_board,
    create_auth_token,
    read_auth_data,
    get_any_list_by_id,
    is_card_template,
    Board,
    List,
)


@cache
def _get_list(board: Board, list_id: str) -> List:
    return get_any_list_by_id(board, list_id)


@cache
def get_list_name(board: Board, list_id: str) -> str:
    tlist = _get_list(board, list_id)
    return tlist.name  # type: ignore[attr-defined]


@cache
def get_list_closed(board: Board, list_id: str) -> bool:
    tlist = _get_list(board, list_id)
    return tlist.closed  # type: ignore[attr-defined]


def process_cards(board_key: str, settings: argparse.Namespace) -> None:
    try:
        board = get_board(board_key, board_key, verbosity=settings.verbose)
    except trello.exceptions.Unauthorized:
        board = get_board(
            board_key,
            board_key,
            verbosity=settings.verbose,
            auth=create_auth_token(read_auth_data()),
        )
    cards_iter = None
    if settings.filter_list is None:
        if settings.print_archived:
            cards_iter = board.all_cards()
        else:
            cards_iter = board.open_cards()
    else:
        tlists = [
            tlist
            for tlist in board.list_lists()
            if (
                (
                    tlist.name == settings.filter_list  # type: ignore[attr-exists]
                    or tlist.id == settings.filter_list  # type: ignore[attr-exists]
                )
                and (
                    not tlist.closed  # type: ignore[attr-exists]
                    or settings.print_archived
                )
            )
        ]
        assert len(tlists) > 0, f"No lists matching '{settings.filter_list}' found"
        card_filter = "all" if settings.print_archived else "open"
        cards_iter = itertools.chain.from_iterable(
            [
                tlist.list_cards(card_filter=card_filter)  # type: ignore[attr-exists]
                for tlist in tlists
            ]
        )
    assert cards_iter is not None
    for card in cards_iter:
        list_id = cast(str, card.list_id)  # type: ignore[attr-exists]
        assert isinstance(list_id, str)
        is_card_closed = cast(bool, card.closed)  # type: ignore[attr-exists]
        assert isinstance(is_card_closed, bool)
        is_list_closed = get_list_closed(board, list_id)
        closed = is_card_closed or is_list_closed
        if not closed or settings.print_archived:
            status = ""
            fields: list[str] = []
            if settings.list:
                status += "#" if is_list_closed else " "
                status += "#" if is_card_closed else " "
                if settings.verbose > 0:
                    fields.append(list_id)
                fields.append(get_list_name(board, list_id))
            else:
                status += "#" if closed else " "
            if settings.verbose > 0:
                card_id = card.id  # type: ignore[attr-exists]
                assert isinstance(card_id, str)
                fields.append(card_id)
            card_name = card.name  # type: ignore[attr-exists]
            assert isinstance(card_name, str)
            fields.append(card_name)
            if settings.description:
                card_desc = card.description  # type: ignore[attr-exists]
                assert isinstance(card_desc, str)
                fields.append(card_desc)
            if settings.is_template:
                fields.append(str(is_card_template(card)))
            print("{:3s} {}".format(status, ", ".join([repr(f) for f in fields])))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("-d", "--description", action="store_true")
    parser.add_argument("-t", "--is-template", action="store_true")
    parser.add_argument("-a", "--print-archived", action="store_true")
    parser.add_argument("-l", "--filter-list", metavar="LIST_NAME_OR_ID")
    parser.add_argument("--list", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("board")
    settings = parser.parse_args()
    if settings.list is None:
        settings.list = settings.filter_list is None
    return settings


def main():
    settings = parse_args()
    process_cards(settings.board, settings)


if __name__ == "__main__":
    main()
