#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Create tasks based on arguments.
import argparse
import sys
import trello.exceptions  # type: ignore[import-untyped]
from bert_trello import (
    get_board,
    get_any_list_by_id,
    get_any_list_by_name,
    create_cards_with_info,
    get_or_create_cards_with_info,
    create_auth_token,
    read_auth_data,
    Board,
    List,
    CardInfo,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("board")
    parser.add_argument("list")
    parser.add_argument("title")
    parser.add_argument("description", nargs="?")
    parser.add_argument("-m", "--if-missing", action="store_true")
    parser.add_argument("-v", "--verbose", action="count", default=0)
    settings = parser.parse_args()
    return settings


def get_list_by_id_or_name(
    board: Board, list_id_or_name: str, verbosity: int = 0
) -> List:
    try:
        tlist = get_any_list_by_id(board, list_id_or_name)
        assert tlist is not None
        if verbosity >= 1:
            tlist_name = tlist.name  # type: ignore
            tlist_id = tlist.name  # type: ignore
            print(f"Selected list  '{tlist_name}' ({tlist_id}) by ID", file=sys.stderr)
    except trello.exceptions.ResourceUnavailable:
        tlist = get_any_list_by_name(board, list_id_or_name)
        assert tlist is not None
        if verbosity >= 1:
            tlist_name = tlist.name  # type: ignore
            tlist_id = tlist.name  # type: ignore
            print(
                f"Selected list  '{tlist_name}' ({tlist_id}) by name", file=sys.stderr
            )
    return tlist


def main() -> None:
    settings = parse_args()
    try:
        board = get_board(settings.board, settings.board, verbosity=settings.verbose)
    except trello.exceptions.Unauthorized:
        board = get_board(
            settings.board,
            settings.board,
            verbosity=settings.verbose,
            auth=create_auth_token(read_auth_data()),
        )
    tlist = get_list_by_id_or_name(board, settings.list)
    card = [CardInfo(name=settings.title, desc=settings.description)]
    if settings.if_missing:
        get_or_create_cards_with_info(tlist, card, verbosity=settings.verbose)
    else:
        create_cards_with_info(tlist, card, verbosity=settings.verbose)


if __name__ == "__main__":
    main()
