#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Show all duplicate cards from a board (by default, 'bert active').
# Template cards are ignored unless they are themselves duplicate.
import argparse
from collections import defaultdict
from functools import cache
import re
import sys
import trello.exceptions
from typing import Callable
from bert_trello import (
    get_board,
    create_auth_token,
    read_auth_data,
    get_any_list_by_id,
    is_card_template,
    print_cards,
)


def create_level_1():
    # Note: specifying the factory argument by name (default_factory=...)
    # as documented on docs.python.org fails with Python 3.11
    return defaultdict(list)


def create_level_2():
    return defaultdict(create_level_1)


def name_is_done_list(list_name: str) -> bool:
    return re.search(r"\b(?:done|gotovo)\b", list_name, re.IGNORECASE)


@cache
def is_done_list(board, list_id):
    tlist = get_any_list_by_id(board, list_id)
    return name_is_done_list(tlist.name)


def ignore_done_lists(cards):
    return (c for c in cards if not is_done_list(c.board, c.list_id))


def find_list(board: trello.Board, *, name_check: Callable[[str], bool]) -> trello.List:
    done_lists = [
        tlist
        for tlist in board.list_lists()
        if not tlist.closed and name_check(tlist.name)
    ]
    if not done_lists:
        raise ValueError(f"No 'done' list found on board {board.name!r}.")
    if len(done_lists) > 1:
        print(
            f"Warning: Multiple 'done' lists found on board {board.name!r}: "
            f" using {done_lists[0].name!r} and ignoring"
            + ", ".join(repr(tlist.name) for tlist in done_lists[1:])
        )
    return done_lists[0]


def handle_cards(cards, settings, *, show_template=False):
    pcards = print_cards(
        cards,
        show_index=True if settings.ask else False,
        show_template=show_template,
        show_start=True,
        show_due=True,
        newline_before_start_due=not (settings.one_line or settings.ask),
        newline_before_url=not (settings.one_line or settings.ask),
    )
    if settings.ask:
        done_list: trello.List | None = None
        for i, card in enumerate(pcards):
            while True:
                response = (
                    input(
                        f"  What to do with card [{i+1}] {card.short_url}? "
                        "(r)emove, (a)rchive, move to (d)one, (s)kip: "
                    )
                    .strip()
                    .lower()
                )
                if response == "r":
                    card.delete()
                    print(f"Removed card {card.id!r}.")
                    break
                elif response == "a":
                    card.set_closed(True)
                    print(f"Archived card {card.id!r}.")
                    break
                elif response == "d":
                    if done_list is None:
                        try:
                            done_list = find_list(
                                card.board, name_check=name_is_done_list
                            )
                        except ValueError:
                            print(
                                f"No 'done' list found on board {card.board.name!r};"
                                " cannot move card."
                            )
                            continue
                    card.change_list(done_list.id)
                    print(f"Moved card {card.id!r} to list {done_list.name!r}.")
                    break
                elif response == "s":
                    print(f"Skipped card {card.id!r}.")
                    break
                else:
                    print("  Please answer 'r', 'a', 'd', or 's'.")


def process_cards(board_key, settings):
    try:
        board = get_board(board_key, board_key, verbosity=settings.verbosity)
    except trello.exceptions.Unauthorized:
        board = get_board(
            board_key,
            board_key,
            verbosity=settings.verbosity,
            auth=create_auth_token(read_auth_data()),
        )
    seen = create_level_2()
    cards_iter = board.open_cards()
    if settings.card_filter:
        cards_iter = settings.card_filter(cards_iter)
    for card in cards_iter:
        cards = seen[str(card.name)][is_card_template(card)]
        cards.append(card)
        if settings.verbosity >= 0:
            # NOTE: does not follow the specified output settings
            print("+" if len(cards) > 1 else ".", end="", file=sys.stderr, flush=True)
    if settings.verbosity >= 0:
        print(file=sys.stderr, flush=True)
    for name in sorted(seen.keys()):
        name_dict = seen[name]
        non_templates = name_dict.get(False, [])
        templates = name_dict.get(True, [])
        if settings.group_with_templates:
            show = (len(non_templates) + len(templates)) >= settings.threshold
            if show:
                print(f"{name!r} (including templates):")
                handle_cards([*non_templates, *templates], settings, show_template=True)
        else:
            show_cards = len(non_templates) >= settings.threshold
            show_templates = len(templates) >= settings.threshold
            if show_cards:
                print(f"{name!r} (cards):")
                handle_cards(non_templates, settings)
                if settings.show_templates_with_cards:
                    if show_templates:
                        print("  matching templates:  see below")
                    elif templates:
                        # The number of templates has to be < threshold, but
                        # the threshold could have been modified so that
                        # there are multiple. So we use plural.
                        print("  matching templates:")
                        handle_cards(templates, settings)
            if show_templates:
                print(f"{name!r} (templates):")
                handle_cards(templates, settings)
                if settings.show_cards_with_templates:
                    if show_cards:
                        print("  matching cards:  see above")
                    elif non_templates:
                        # See above; use plural.
                        print("  matching cards:")
                        handle_cards(non_templates, settings)


def parse_args():
    parser = argparse.ArgumentParser(
        description=("Show duplicate cards and templates on a board.")
    )
    parser.add_argument(
        "-v",
        "--verbose",
        dest="verbosity",
        action="count",
        default=0,
        help="Be more verbose. Can be repeated.",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        dest="verbosity",
        action="store_const",
        const=-1,
        help="Be non-verbose.",
    )
    parser.add_argument(
        "-t",
        "--show-templates-with-cards",
        "--show-templates",
        action="store_true",
        help=(
            "When showing non-template cards, also"
            " separately show the corresponding templates."
            " (Normally the cards and the templates are"
            " shown independently.)"
            " This is meaningless with"
            " --group-with-templates."
        ),
    )
    parser.add_argument(
        "-c",
        "--show-cards-with-templates",
        "--show-cards",
        action="store_true",
        help=(
            "When showing templates, also separately show"
            " the corresponding non-template cards."
            " (Normally the cards and the templates are"
            " shown independently.)"
            " This is meaningless with"
            " --group-with-templates."
        ),
    )
    parser.add_argument(
        "-T",
        "--group-with-templates",
        "--with-templates",
        action="store_true",
        help=(
            "Group non-template cards and templates"
            " together, and treat any 2 cards (including"
            " templates *and* non-template cards) as a"
            " duplicate."
        ),
    )
    parser.add_argument(
        "-1",
        "--one-line",
        "--one_line",
        action="store_true",
        help=("Show each card's info on a single line."),
    )
    parser.add_argument(
        "-n",
        "--threshold",
        metavar="N",
        action="store",
        type=int,
        default=2,
        help=(
            "Look for >= N cards of a given type, instead"
            " of >= 2, when looking for duplicates."
        ),
    )
    parser.add_argument(
        "-D",
        "--ignore-done",
        "--ignore_done",
        dest="card_filter",
        action="store_const",
        const=ignore_done_lists,
        help='Ignore "done" lists by name.',
    )
    parser.add_argument(
        "--ask",
        action="store_true",
        help="Ask the user what to do with each duplicate card.",
    )
    parser.add_argument(
        "board", nargs="?", default="6531ac71f384b1da10602fce"  # "bert active"
    )
    settings = parser.parse_args()
    if settings.threshold < 1:
        parser.error("--threshold must specify a positive integer.")
    # TODO warn about combinations that don't make sense...
    return settings


def main():
    settings = parse_args()
    process_cards(settings.board, settings)


if __name__ == "__main__":
    main()
