#!/home/bert/.local/lib/python/venv/tasks/bin/python3
# Delete archived cards from the specified board.
import argparse
import sys
import trello.exceptions  # type: ignore[import-untyped]
from typing import cast
from bert_trello import create_auth_token, get_board, read_auth_data


def process_cards(board_key: str, settings: argparse.Namespace) -> None:
    try:
        board = get_board(board_key, board_key, verbosity=settings.verbose)
    except trello.exceptions.Unauthorized:
        board = get_board(
            board_key,
            board_key,
            verbosity=settings.verbose,
            auth=create_auth_token(read_auth_data()),
        )
    if settings.verbose >= 1:
        print("Checking cards.", file=sys.stderr)
    for card in board.closed_cards():
        card_name = card.name  # preserve before deletion  # type: ignore[attr-defined]
        if settings.filter_list is not None:
            tlist = card.get_list()
            tlist_name = tlist.name  # type: ignore[attr-defined]
            tlist_id = tlist.id  # type: ignore[attr-defined]
            if not (
                tlist_name == settings.filter_list or tlist_id == settings.filter_list
            ):
                print(
                    f"(T) Keeping archived card '{card_name}' "
                    "because of list filter.",
                    file=sys.stderr,
                )
                continue  # skip this card
        if not settings.dry_run:
            card.delete()
            print(f"(T) Archived card '{card_name}' deleted.", file=sys.stderr)
        else:
            print(f"(T) Archived card '{card_name}' would be deleted.", file=sys.stderr)
    if settings.verbose >= 1:
        print("Checking lists.", file=sys.stderr)
    for tlist in board.closed_lists():
        if settings.filter_list is not None:
            tlist_name = tlist.name  # type: ignore[attr-defined]
            tlist_id = tlist.id  # type: ignore[attr-defined]
            if not (
                tlist_name == settings.filter_list or tlist_id == settings.filter_list
            ):
                for card in tlist.list_cards():  # type: ignore[attr-defined]
                    card_name = cast(str, card.name)  # type: ignore[attr-defined]
                    assert isinstance(card_name, str)
                    print(
                        f"(T) Keeping card '{card_name}' from archived list "
                        "because of list filter.",
                        file=sys.stderr,
                    )
                continue  # skip this list
        for card in tlist.list_cards():  # type: ignore[attr-defined]
            card_name = cast(str, card.name)  # type: ignore[attr-defined]
            assert isinstance(card_name, str)
            if not settings.dry_run:
                card.delete()
                print(
                    f"(T) Card '{card_name}' from archived list deleted.",
                    file=sys.stderr,
                )
            else:
                print(
                    f"(T) Card '{card_name}' from archived list" " would be deleted.",
                    file=sys.stderr,
                )
    if settings.verbose >= 2:
        print("Done.", file=sys.stderr)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("-l", "--filter-list", metavar="LIST_NAME_OR_ID")
    parser.add_argument("-n", "--dry-run", action="store_true")
    parser.add_argument("board")
    settings = parser.parse_args()
    return settings


def main() -> None:
    settings = parse_args()
    process_cards(settings.board, settings)


if __name__ == "__main__":
    main()
