#!/home/bert/.local/lib/python/venv/default/bin/python

import argparse
import arrow
import icalendar.cal
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="count", default=0)
    parser.add_argument("file", nargs="?", metavar="FILE|-")
    settings = parser.parse_args()
    return settings


if __name__ == "__main__":
    settings = parse_args()
    if settings.file is None:
        settings.file = "-"
    if settings.file == "-":
        data = sys.stdin.buffer.read()
    else:
        with open(settings.file, "rb") as fh:
            data = fh.read()
    cal = icalendar.cal.Calendar.from_ical(data)
    for c in cal.subcomponents:
        if not ("dtstart" in c or "rdate" in c):
            continue
        if settings.verbose:
            print(f"{c['summary']}:")
            if "dtstart" in c:
                print(arrow.get(c["dtstart"].dt).strftime("  s %Y-%m-%d: %A"))
            if "rdate" in c:
                for rdate in c["rdate"]:
                    for prop in rdate.dts:
                        print(arrow.get(prop.dt).strftime("  r %Y-%m-%d: %A"))
        else:
            if "dtstart" in c:
                print(arrow.get(c["dtstart"].dt).strftime("%A"))
            if "rdate" in c:
                for rdate in c["rdate"]:
                    for prop in rdate.dts:
                        print(arrow.get(prop.dt).strftime("%A"))
