#!/bin/bash

source "$(dirname "$(realpath "$0")")"/ll-functions.bash

case "$1" in
    --child)    shift ;;
    *)          exec sudo "$0" --child "$@" ; exit 1 ;;
esac

user=luka

while [ "$#" -gt 0 ]; do
    case "$1" in
        -n)     run=(echo '>'); shift ;;
        -q)     log=(true); shift ;;
        -u)     user="$2"; shift; shift ;;
        -*)     echo "Unknown flag '$1'!" >&2; exit 1 ;;
        *)      echo "Unknown argument '$1'!" >&2; exit 1 ;;
    esac
done

lock_account "$user"

# lock the session
session_found=
for s in $(get_user_sessions "$user"); do
    session_found=yes
    case "$s" in
        lxqt-session)
            "${log[@]}" "Trying to lock the screen..." >&2
            if ! run_as_user "$user" \
                     xscreensaver-command -lock; then
                "${log[@]}" "...$(failed)." >&2
            else
                "${log[@]}" "...$(is_done)." >&2
            fi
            ;;
        *)
            "${log[@]}" "Unknown session '$s', locking skipped." >&2
            ;;
    esac
done
if [ -z "$session_found" ]; then
    "${log[@]}" "$(warn)$(user2name "$user") does not seem to be logged in.$(end)" >&2
fi

# lock binaries for ALL users
lock_dir /opt/minecraft-launcher
lock_executable_file /usr/bin/minecraft-launcher
lock_executable_file /bin/minecraft-launcher
lock_dir /opt/multimc
lock_flatpak_graphics io.mrarm.mcpelauncher

"${log[@]}" "(Note: Discord app was not killed.)" >&2

clear_relock_queue

"${log[@]}" "(Note: Minecraft apps, if any, were not killed.)" >&2
