#!/bin/bash

source "$(dirname "$(realpath "$0")")"/ll-functions.bash

case "$1" in
    --child)    shift ;;
    *)          exec sudo "$0" --child "$@" ; exit 1 ;;
esac

user=luka

while [ "$#" -gt 0 ]; do
    case "$1" in
        -n)     run=(echo '>'); shift ;;
        -q)     log=(true); shift ;;
        -u)     user="$2"; shift; shift ;;
        -*)     echo "$(bad)Unknown flag '$1'!$(end)" >&2; exit 1 ;;
        *)      break ;;
    esac
done

timespec="$1"; shift  # note: okay if missing
if [ "$#" -gt 0 ]; then
    echo "$(bad)Unexpected argument '$1'!$(end)" >&2; exit 1
fi

timestamp="$(parse_schedule_time "$timespec")"
if [ -z "$timestamp" ]; then
    exit 2
fi

"${log[@]}" "Trying to schedule locking at $(timespec_for_at "$timestamp")" >&2

schedule_lock "$user" "$timestamp"
