#!/bin/bash

source "$(dirname "$(realpath "$0")")"/ll-functions.bash

today="$(date +%Y-%m-%d)"
case " ${no_unlock_days[*]} " in
    *" $today "*)
        echo "Today is not a screen day." >&2
        exit 33 ;;
esac

case "$1" in
    --child)    shift ;;
    *)          exec sudo "$0" --child "$@" ; exit 1 ;;
esac

user=luka

while [ "$#" -gt 0 ]; do
    case "$1" in
        -n)     run=(echo '>'); shift ;;
        -q)     log=(true); shift ;;
        -u)     user="$2"; shift; shift ;;
        -*)     echo "Unknown flag '$1'!" >&2; exit 1 ;;
        *)      echo "Unknown argument '$1'!" >&2; exit 1 ;;
    esac
done

unlock_account "$user"

# unlock binaries for ALL users
unlock_dir /opt/minecraft-launcher
unlock_executable_file /usr/bin/minecraft-launcher
unlock_executable_file /bin/minecraft-launcher
unlock_dir /opt/multimc
unlock_flatpak io.mrarm.mcpelauncher
unlock_flatpak com.valvesoftware.Steam
unlock_flatpak com.discordapp.Discord

schedule_lock_at_bedtime "$user"

"${log[@]}" "(Note: timed unlocking is still not implemented.)" >&2
