#!/usr/bin/perl
# *Utterly erase* ID3 tags from a file
use warnings;
use strict;

use Getopt::Long;

our $BACKUP = 1;
GetOptions('force|f'   => sub { $BACKUP = 0; },
	  ) or die;

foreach my $file (@ARGV) {
  if ($BACKUP) {
    my $backup = $file . '.bak';
    unlink $backup;  # if it fails that's OK
    rename $file, $backup
      or die "rename($file -> $backup): $!";
    system 'cp', $backup, $file
      and warn("Copy failed"),
	(rename $backup, $file or warn "rename($backup -> $file): $!"),
	  exit 1;
  }

  # '-Q' isn't actually very quiet.
  open STDOUT, '>', '/dev/null';
  open STDERR, '>', '/dev/null';

  system 'eyeD3', '-Q', '--remove-all', $file;
}
