#!/bin/bash
# Update the lo-fi directory from the local directory (not including
# "from_SanDisk_player"). Assumes there were no file name changes to
# existing files in one vs. the other! If you aren't sure, try
# ../lo-fi/compare-list-of-files.sh...

cd "$(dirname "$0")" || exit 1
find * -name 'from_SanDisk_player' -prune -o -type d -prune -print0 \
    | xargs -0 -r /scratch/music/lo-fi/reduce-bitrate.sh -P "$(nproc)"
