#!/usr/bin/python3
import argparse
import datetime as dt
import re


def process_logfile(path, settings):
    def format_hms(s):
        m = s // 60
        s -= m * 60
        h = m // 60
        m -= h * 60
        return f"{h:02d}:{m:02d}:{s:02d}"

    def replace_plus(match):
        nonlocal start
        nonlocal prev
        stamp = match.group(1)
        time = dt.datetime.strptime(stamp, '%Y-%m-%d %H:%M:%S')
        if start is None:
            start = time
            prev = time
            since_prev = '(start)'
        else:
            since_prev = '+' + format_hms(int((time - prev).total_seconds()))
        since_start = '@+' + format_hms(int((time - start).total_seconds()))
        prev = time
        return f"[{stamp}]:  {since_start:>10s}  {since_prev:>9s}"

    def replace_minus(match):
        nonlocal end
        nonlocal next
        stamp = match.group(1)
        time = dt.datetime.strptime(stamp, '%Y-%m-%d %H:%M:%S')
        if end is None:  # assumes going backwards
            end = time
            next = time
            since_next = '(end)'
        else:
            since_next = '-' + format_hms(int((next - time).total_seconds()))
        since_end = '@-' + format_hms(int((end - time).total_seconds()))
        next = time
        return f"[{stamp}]:  {since_next:>9s}  {since_end:>10s}"

    with open(path, 'r') as f:
        lines = [line.rstrip() for line in f if re.search(r'^-- ', line)]

    end = None
    next = None
    lines = reversed([re.sub(r'\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]',
                             replace_minus, line)
                      for line in reversed(lines)])
    start = None
    prev = None
    lines = [re.sub(r'\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]:',
                    replace_plus, line)
             for line in lines]

    if settings.strip_time:
        lines = [re.sub(r'\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]:\s+',
                        '', line)
                 for line in lines]
    if settings.strip_color:
        lines = [re.sub(r'\033\[\d+(?:;\d+)*m', '', line)
                 for line in lines]
    if settings.duration:
        lines = [re.sub((r'@\+\d{2,}:\d{2}:\d{2}\s+'
                         r'(?:\+\d{2,}:\d{2}:\d{2}|\(start\))\s+'
                         r'(?:-(\d{2,}:\d{2}:\d{2})|(\(end\)))\s+'
                         r'@-\d{2,}:\d{2}:\d{2}'),
                        r'\1\2', line)
                 for line in lines
                 if re.search(r'(?:Backing up|Cleaning up)', line)]

    print(path)
    for line in lines:
        print(line)
    print('')


def parse_args():
    parser = argparse.ArgumentParser(
        description='Read a `raid-backup` log and show timing of steps.'
    )
    parser.add_argument('--keep-time', dest='strip_time', action='store_false')
    parser.add_argument('--strip-color', action='store_true')
    parser.add_argument('--duration', action='store_true')
    parser.add_argument('logfile', nargs='+', metavar='LOGFILE',
                        help='Log file(s) to read.')
    settings = parser.parse_args()
    return settings


def main():
    settings = parse_args()
    for path in settings.logfile:
        process_logfile(path, settings)


if __name__ == "__main__":
    main()
