#!/bin/bash
# Back up a root partition to a partition on a SATA HDD.

script="$(dirname "$(realpath "$0")")/../backup_partition.py"
if [ ! -e "$script" ]; then
    echo "Could not find backup_partition.py script" >&2; exit 1
fi

passthrough=()
while [ "$#" -gt 0 ]; do
    case "$1" in
        -v|--verbose)  passthrough+=("--verbose"); shift ;;
        -n|--dry-run)  passthrough+=("--dry-run"); shift ;;
        -*)  echo "Unknown flag '$1'" 2>&1; exit 1 ;;
        *)   echo "Unknown argument '$1'" 2>&1; exit 1 ;;
    esac
done

if [ "$(id -u)" != 0 ]; then
    echo "Warning: not root.  (Try with ssudo?)" >&2
fi

"$script" "${passthrough[@]}" \
          --write-times /common/backups/last_backup.root_hdd \
          -X .cache -X .gvfs \
          --root \
          LABEL="root" LABEL="hdd_root" \
          --efi \
          LABEL="EFI_SYS" LABEL="HDDEFISYS"
