#!/bin/bash
host_name=aunt-louisa
host_addr=10.10.80.80

source "$(dirname "$(realpath -e "$0")")"/../sysadmin/mount-umount.sh || exit 9

if [[ "$#" -eq 0 ]]; then
    echo "No shares specified!" >&2
    exit 2
fi
for share in "$@"; do
    do_mount_smb "$host_name" "$host_addr" "$share" || exit 1
done
