#!/bin/bash
host_name=aunt-louisa
host_addr=10.10.80.80

source "$(dirname "$(realpath -e "$0")")"/../sysadmin/mount-umount.sh || exit 9

Usage () {
    local exit_code="${1:-0}"; shift
    local message
    case "${exit_code}" in
        [0-9]|[1-9][0-9]|[1-9][0-9][0-9]|-[0-9]|-[1-9][0-9]|-[1-9][0-9][0-9]) ;;
        *)
            set -- "Internal error: invalid exit code '${exit_code}'" "$@"
            exit_code=255 ;;
    esac
    if [[ "${exit_code}" -ne 0 ]]; then
        exec >&2
    fi
    if [[ "$#" -gt 0 ]]; then
        for message in "$@"; do
            echo "${message}"
        done
        echo ""
    fi
    echo "Usage: $(basename "$0") SMB_SHARE ..."
    echo "  or:  $(basename "$0")  # to unmount all smb mounts from ${host_name}"
    exit "${exit_code}"
}

for arg in "$@"; do
    if [[ "${arg}" == "--help" ]] || [[ "${arg}" == "-h" ]] || [[ "${arg}" == "-?" ]]; then
        Usage 0
    elif [[ "${arg}" == -* ]]; then
        Usage 1 "Unknown flag '${arg}'"
    fi
done
if [[ "$#" -eq 0 ]]; then
    set -- $(get_smb_shares "$host_name")
    if [[ "$#" -eq 0 ]]; then
        Usage 2 "No shares specified and none found."
    else
        echo "Will unmount: $*" >&2
    fi
fi
result=0
for share in "$@"; do
    if ! do_umount_smb "$host_name" "$host_addr" "$share"; then
        result=9
    fi
done
