#!/bin/bash

host_name=aunt-louisa
host_addr=10.10.80.80
share=scratch

source "$(dirname "$(realpath -e "$0")")"/../sysadmin/mount-umount.sh || exit 9
do_umount_smb "$host_name" "$host_addr" "$share"
