#!/bin/bash
cd "$(dirname "$0")" || exit 1
echo "Processing transactions..." >&2
rm -f *-combined.csv *-uniform.csv finances-*.csv >/dev/null 2>&1
./combine_cam_trust.py ../data-*/CamTrust-RelPlus-transactions-*.csv || exit 1
./combine_venmo.py ../data-*/Venmo-transactions-*.csv || exit 1
./combine_cap_one.py ../data-*/CapitalOne-transactions-*.csv || exit 1
./combine_discover.py ../data-*/Discover-transactions-*.csv || exit 1
echo "done!" >&2
echo "Merging..." >&2
./merge_uniform.py *-uniform.csv || exit 1
echo "done!" >&2
